### PR TITLE
Redeemable

### PR DESCRIPTION
**Pull request by elv-serban**
### Implements:

- a new Redeemable contract that allows add/remove and redeem of 'offers' (max 256 offers - using a uint256 as a bitmap)
- elv_tradable_full redeemOffer and redeemOfferSigned (override the Redeemable virtual method to require caller is owner of token, and implement the delegated call to redeemOfferSigned)
- added foundry forge test framework for subdirectory 'src'
  - foundry requires solc 0.6+ and we use 0.5 in the legacy code, which is why I set up a new directory for new code

### Implementation notes:

- I created src/redeemable.sol and copied it under tradable/redeemable.sol with a few modifications:
  - MinterRole import path
- I created a dummy MinterRole contract in 'src/' so we can test redeemable.sol
- NB the entire contracts repo will be scrubbed cleaned and upgraded and at that time this problem will no longer exist

### Remaining problems to solve:

- unify the two redeemable.sol files
- run full elvmaster test on the new elv_tradable functions

### CODE REVIEW

**Review by elv-wayne — COMMENTED** [review]
Looks good to me other than tradable/redeemable.sol is duplicate of src/redeemable.sol ?

**Comment by elv-nate** [comment]
Aside from some small comments I made about testing which are MinterOnly, this looks good to me. The design unfortunately makes it hard to test redeemable tokens without a much more involved test, as you need a token to implement it and such.

**Comment by elv-Tom** [comment]
Very efficient, use a minimum of gas, and works perfectly. I added a script here : https://github.com/eluv-io/contracts/blob/redeemable/script/tradable/redeemable.s.sol 
Because the contract will not be deployed, we can add the 'abstract' key word for this contract.

**Review by elv-peter — APPROVED** [review]
Looks good. I'd copy `redeemable.sol` in the build script rather than having duplicate files in version control

**Pull request merged**
