### PR TITLE
upgrade-eth-1.9.19

### PR DESCRIPTION
**Pull request by elv-preethi**
relates to [fabric #226](https://github.com/qluvio/content-fabric/issues/2226)

rm U256 abi type (not supported in eth 1.9.19 abi package)

### CODE REVIEW

**Comment by elv-preethi** [comment]
Update :

1. `abi.U256` is not supported in eth 1.9.19 and this affects go code generated with older version of abigen. So updated `build/base_content_space.go` with abigen v1.9.19.
2.  for abigen v1.9.19
```
cd /WS/pkg/mod/github.com/ethereum/go-ethereum@v1.9.19 
go install ./cmd/abigen 
```
3.  updated build.sh to use abigen binary path from $ABIGEN variable:
```
export ABIGEN = "<abigen-bin-path>"
./build.sh
``` 
4. also, removed `abi.U256` manually from `build/20190331`, `build/20200206`, `build/20200803`

**Comment by elv-preethi** [comment]
Note : below test failed in elv-master
```
--- FAIL: TestTransManSuite (57.82s)
    --- FAIL: TestTransManSuite/TestContentObjHelperCompile (1.43s)
        trans_man_test.go:72:
            	Error Trace:	trans_man_test.go:72
            	Error:      	Should be true
            	Test:       	TestTransManSuite/TestContentObjHelperCompile
            	Messages:   	code in helper needs to be updated when BaseContent is modified
FAIL
FAIL	github.com/qluvio/elv-master/server/trans/trans_test	59.990s
```

It was because baseContent binary generated by abigen was different from the one present in contract's helper method. Resolved it by copying the baseContent binary from abigen to contract and re-running abigen.

**Comment by elv-peter** [comment]
Do we need to rebase this on develop and rebuild the output files?

**Comment by elv-gilles** [comment]
> Do we need to rebase this on develop and rebuild the output files?

hhmm... it is based on develop (i merged it) and the go bindings have been updated since the code for bindings changed in go-ethereum.
So I don't think any other output need to be updated.

**Review by elv-peter — APPROVED** [review]

**Pull request merged**
