### PR TITLE
Delete version fix

### PR DESCRIPTION
**Pull request by elv-marc**
As mentioned by email, I think this is the cause of the delete version oddity.

If that makes sense, we can swap the base content factory with a new one and try.

### CODE REVIEW

**Comment by paulgoleary** [comment]
Yeah this is a problem. The current code doesn't handle deleting the most recent version correctly.

The PR includes quite a few unrelated changes. Was that intentional?

If not, I can pull the changes out and submit a separate PR.

**Comment by elv-marc** [comment]
I only committed editable.sol, the other modified files are there because of where I started my branch from, which is the v3 changes.
Best is to just merge the changes from editable.sol.

**Comment by paulgoleary** [comment]
Agreed. I'll create a new branch + PR.

**Comment by paulgoleary** [comment]
Closing. Now subsumed by `authv3changes` - #52.

**Pull request closed without merging**
